name: Tests
'on':
  push:
    branches:
      - main
  pull_request: null
  workflow_dispatch: null

jobs:
  permission_check:
    runs-on: ubuntu-latest
    outputs:
      can-write: '${{ steps.check.outputs.can-write }}'
    env:
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
    steps:
      - id: check
        run: |
          # If the AWS_ACCESS_KEY_ID secret is MIA we can't run tests
          if [[ -z "$AWS_ACCESS_KEY_ID" ]]; then
              echo "can-write=false" >> $GITHUB_OUTPUT
          else
              echo "can-write=true" >> $GITHUB_OUTPUT
          fi
          
  test-action:
    runs-on: ubuntu-latest
    needs:
      - permission_check
    if: needs.permission_check.outputs.can-write == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Provision DCE
        uses: ./
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          email: colin.hutchinson+gha@observeinc.com

      - name: AWS Identity (DCE)
        run: aws sts get-caller-identity

      - name: Decomission DCE
        uses: ./
        with:
          action-type: decommission
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          email: colin.hutchinson+gha@observeinc.com
